on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm run test:lint
  build-push:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: chainsaw2k
          password: ${{ secrets.PRIVATE_REPO_WRITE_PACKAGES_PERMS }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile.worker
          tags: ghcr.io/chainsaw2k/ntu-worker
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile.cli
          tags: ghcr.io/chainsaw2k/ntu-cli